# Generated by Django 4.1 on 2023-01-28 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
